# Generated by Django 2.2 on 2019-05-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190512_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='price',
        ),
    ]
